config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'
  resources :artists, only: [:index] do 
    resources :shows, only: [:index, :show] do
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :shows
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show]

  def index
    @artists = Artist.all
  end

  private

    def set_artist
      @artist = Artist.find(params[:id])
    end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show]

  def index
    @artist = Artist.find(params[:artist_id])
    @shows = Show.where("artist_id = #{params[:artist_id]}")
  end

  def show
    @artist = Artist.find(params[:artist_id])
    @show = Show.find(params[:id])
  end

  private

    def set_show
      @show = Show.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
        <% artist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :img %>
    <%= form.text_field :img %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<body id="artist-body">

    <div class="container index">
    
        <h1 class="title"><big><strong>In Case You Missed It</strong></big></h1>
    
        <% @artists.sort_by{ |artist| artist.name }.each do |artist| %>
            <div class="artists">
                
                <div class="artist-image">
                    <a href="/artists/<%= artist.id %>/shows">
                        <img class="artist-img" src=<%= artist.img %> alt=<%= artist.name %> >
                    </a>
                </div>
            
                <div class="artist-name">
                    <a href="/artists/<%= artist.id %>/shows">
                        <h1><%= artist.name %></h1>
                    </a>
                </div>

            </div>
        <% end %> 

    </div>

</body>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<h1> <%=@artist.name%> </h1>

<%shows = @artist.shows%>

<h1>Shows:</h1>
<% @shows.each do |show| %>
<h2> <%= show.location %> </h2>
<h4> <%= show.date %> </h4>
  <img src="<%= show.img %>" >
<% end %>
<%= link_to 'Back', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ICYMI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <link rel="icon" href="https://cdn2.iconfinder.com/data/icons/kids/128x128/apps/multimedia.png"
    type="image/x-icon">

    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shows/_form.html.erb
<%= form_with(model: show, local: true) do |form| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
        <% show.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :img %>
    <%= form.text_field :img %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<p id="notice"><%= notice %></p>

<body id="concert-body"> 

    <div class="container index">

        <% if false %>
        <nav class="title">
        <a href="/artists"> <button type="button" class="btn btn-primary">back</button> </a>
        </nav>
        <% end %>
        
        <h1 class="title"><strong><%= @artist.name %></strong></h1>
        

        <% @shows.each do |show| %>
            <div class="shows">
            
                <div class="show-image">
                    <a href="/artists/<%= @artist.id %>/shows/<%= show.id %>">
                        <img class="concert-img" src=<%= show.img %> alt=<%= show.location %> >
                    </a>
                </div>

                <div class="show-info">
                    <a href="/artists/<%= @artist.id %>/shows/<%= show.id %>">
                        <h2 class="index-location"><%= show.location %></h2>
                        <h3 class="index-date"><%= show.date %></h3>
                    </a>
                </div>

            </div>
        <% end %>
    
        <a href="/artists"> <button type="button" class="btn btn-outline" id="to-artists">back</button> </a>
    </div>
</body>

app/views/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<% require 'httparty' %>

<% response = HTTParty.get("https://api.setlist.fm/rest/1.0/search/setlists?artistName=#{@artist.name}&date=#{@show.date}&p=1&venueName=#{@show.venue}",headers: { 'x-api-key' => 'xlEeWdnKwBF9fBlUFjU40BOJV9xWkMswV40L', 'Accept' => 'application/json' }) %>

<% data = ActiveSupport::JSON.decode(response.body) %>

<body id="setlist-body">

  <div class="container">

    <h1 id="name"><%= @artist.name %></h1>
    <h2 id="location"><%= data["setlist"][0]["venue"]["name"] %>, <%= @show.location %></h2>
    <h3 id="date"><%= @show.date %></h3>

    <hr>

    <h3 class="sets">Setlist</h3>

    <% sets = data["setlist"][0]["sets"]["set"] %>
  
    <% for j in 0 ... sets.length %>
      <% setlist = data["setlist"][0]["sets"]["set"][j]["song"] %> 
        <% for i in 0 ... setlist.length %>
          <ul>
            <li class="song-list"><%= "#{i + 1}. " %><%= setlist[i]["name"] %></li>
          </ul>  
        <%end%>
          <h5 class="sets"><%= sets.length > 1 && j == 0 ? "Encore" : nil %></h5>
    <% end %>

    <p class="source">
      Source: <a href="<%= data["setlist"][0]["url"] %>" target="_blank" class="setlist-fm">setlist.fm</a>
    </p>
    <a href="/artists/<%= @artist.id %>/shows"> 
      <button type="button" id="to-concerts" class="btn btn-outline">back</button> 
    </a>

  </div>

</body>